config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/auth/:provider/callback', to: 'sessions#create'

  post '/clone', to: 'welcome#clone'
  post '/push', to: 'welcome#push'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    $token = auth_hash['credentials']['token']
    redirect_to '/'
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

require 'open3'
require 'time'

class WelcomeController < ApplicationController
  def clone
    @cmd = <<~CMD
      rm -rf /tmp/test-repo &&
      git clone https://#{$token}:x-oauth-basic@github.com/sahilm/test-repo /tmp/test-repo
    CMD
    @stdout, @stderr, @status = Open3.capture3(@cmd)
    render 'welcome/command'
  end

  def push
    @cmd = <<~CMD
      bash -c '
      export GIT_TERMINAL_PROMPT=0
      git --git-dir /tmp/test-repo/.git config credential.helper ""
      git --git-dir /tmp/test-repo/.git commit -m "#{Time.now.utc.iso8601}" --allow-empty &&
      git --git-dir /tmp/test-repo/.git push https://#{$token}:x-oauth-basic@github.com/sahilm/test-repo master
      '
    CMD
    @stdout, @stderr, @status = Open3.capture3(@cmd)
    render 'welcome/command'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GithubOauthSomethingSomething</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/welcome/clone.html.erb
<p>
  cmd: <%= @cmd %>
</p>
<p>
  stdout: <%= @stdout %>
</p>
<p>
  stderr: <%= @stderr %>
</p>
<p>
  status: <%= @status %>
</p>

app/views/welcome/command.html.erb
<p>
  cmd: <%= @cmd %>
</p>
<p>
  stdout: <%= @stdout %>
</p>
<p>
  stderr: <%= @stderr %>
</p>
<p>
  status: <%= @status %>
</p>

app/views/welcome/index.html.erb
<% if $token %>
  Oauth token: <%= $token %>
  <%= form_tag(clone_path) do %>
    <%= button_tag('clone test-repo in /tmp') %>
  <% end %>
  <%= form_tag(push_path) do %>
    <%= button_tag('commit and push test-repo') %>
  <% end %>
<% else %>
  <%= link_to 'Sign in with Github', '/auth/github' %>
<% end %>